// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package github

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// Autogenerated input type of ChangeUserStatus
type ChangeUserStatusInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId *string `json:"clientMutationId"`
	// The emoji to represent your status. Can either be a native Unicode emoji or an emoji name with colons, e.g., :grinning:.
	Emoji *string `json:"emoji"`
	// If set, the user status will not be shown after this date.
	ExpiresAt *time.Time `json:"expiresAt"`
	// Whether this status should indicate you are not fully available on GraphqlClient, e.g., you are away.
	LimitedAvailability *bool `json:"limitedAvailability"`
	// A short description of your current status.
	Message *string `json:"message"`
	// The ID of the organization whose members will be allowed to see the status. If
	// omitted, the status will be publicly visible.
	OrganizationId *string `json:"organizationId"`
}

// GetClientMutationId returns ChangeUserStatusInput.ClientMutationId, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetClientMutationId() *string { return v.ClientMutationId }

// GetEmoji returns ChangeUserStatusInput.Emoji, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetEmoji() *string { return v.Emoji }

// GetExpiresAt returns ChangeUserStatusInput.ExpiresAt, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetExpiresAt() *time.Time { return v.ExpiresAt }

// GetLimitedAvailability returns ChangeUserStatusInput.LimitedAvailability, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetLimitedAvailability() *bool { return v.LimitedAvailability }

// GetMessage returns ChangeUserStatusInput.Message, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetMessage() *string { return v.Message }

// GetOrganizationId returns ChangeUserStatusInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *ChangeUserStatusInput) GetOrganizationId() *string { return v.OrganizationId }

// __changeUserStatusInput is used internally by genqlient
type __changeUserStatusInput struct {
	Status ChangeUserStatusInput `json:"status"`
}

// GetStatus returns __changeUserStatusInput.Status, and is useful for accessing the field via an interface.
func (v *__changeUserStatusInput) GetStatus() ChangeUserStatusInput { return v.Status }

// __contributionsViewInput is used internally by genqlient
type __contributionsViewInput struct {
	Username string    `json:"username"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

// GetUsername returns __contributionsViewInput.Username, and is useful for accessing the field via an interface.
func (v *__contributionsViewInput) GetUsername() string { return v.Username }

// GetFrom returns __contributionsViewInput.From, and is useful for accessing the field via an interface.
func (v *__contributionsViewInput) GetFrom() time.Time { return v.From }

// GetTo returns __contributionsViewInput.To, and is useful for accessing the field via an interface.
func (v *__contributionsViewInput) GetTo() time.Time { return v.To }

// changeUserStatusChangeUserStatusChangeUserStatusPayload includes the requested fields of the GraphQL type ChangeUserStatusPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of ChangeUserStatus
type changeUserStatusChangeUserStatusChangeUserStatusPayload struct {
	// Your updated status.
	Status *changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus `json:"status"`
}

// GetStatus returns changeUserStatusChangeUserStatusChangeUserStatusPayload.Status, and is useful for accessing the field via an interface.
func (v *changeUserStatusChangeUserStatusChangeUserStatusPayload) GetStatus() *changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus {
	return v.Status
}

// changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus includes the requested fields of the GraphQL type UserStatus.
// The GraphQL type's documentation follows.
//
// The user's description of what they're currently doing.
type changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus struct {
	Id string `json:"id"`
}

// GetId returns changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus.Id, and is useful for accessing the field via an interface.
func (v *changeUserStatusChangeUserStatusChangeUserStatusPayloadStatusUserStatus) GetId() string {
	return v.Id
}

// changeUserStatusResponse is returned by changeUserStatus on success.
type changeUserStatusResponse struct {
	// Update your status on GraphqlClient.
	ChangeUserStatus *changeUserStatusChangeUserStatusChangeUserStatusPayload `json:"changeUserStatus"`
}

// GetChangeUserStatus returns changeUserStatusResponse.ChangeUserStatus, and is useful for accessing the field via an interface.
func (v *changeUserStatusResponse) GetChangeUserStatus() *changeUserStatusChangeUserStatusChangeUserStatusPayload {
	return v.ChangeUserStatus
}

// contributionsViewResponse is returned by contributionsView on success.
type contributionsViewResponse struct {
	// Lookup a user by login.
	User *contributionsViewUser `json:"user"`
}

// GetUser returns contributionsViewResponse.User, and is useful for accessing the field via an interface.
func (v *contributionsViewResponse) GetUser() *contributionsViewUser { return v.User }

// contributionsViewUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GraphqlClient that owns repositories and can make new content.
type contributionsViewUser struct {
	// The collection of contributions this user has made to different repositories.
	ContributionsCollection contributionsViewUserContributionsCollection `json:"contributionsCollection"`
}

// GetContributionsCollection returns contributionsViewUser.ContributionsCollection, and is useful for accessing the field via an interface.
func (v *contributionsViewUser) GetContributionsCollection() contributionsViewUserContributionsCollection {
	return v.ContributionsCollection
}

// contributionsViewUserContributionsCollection includes the requested fields of the GraphQL type ContributionsCollection.
// The GraphQL type's documentation follows.
//
// A contributions collection aggregates contributions such as opened issues and commits created by a user.
type contributionsViewUserContributionsCollection struct {
	// A calendar of this user's contributions on GraphqlClient.
	ContributionCalendar contributionsViewUserContributionsCollectionContributionCalendar `json:"contributionCalendar"`
}

// GetContributionCalendar returns contributionsViewUserContributionsCollection.ContributionCalendar, and is useful for accessing the field via an interface.
func (v *contributionsViewUserContributionsCollection) GetContributionCalendar() contributionsViewUserContributionsCollectionContributionCalendar {
	return v.ContributionCalendar
}

// contributionsViewUserContributionsCollectionContributionCalendar includes the requested fields of the GraphQL type ContributionCalendar.
// The GraphQL type's documentation follows.
//
// A calendar of contributions made on GraphqlClient by a user.
type contributionsViewUserContributionsCollectionContributionCalendar struct {
	// A list of the weeks of contributions in this calendar.
	Weeks []contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek `json:"weeks"`
}

// GetWeeks returns contributionsViewUserContributionsCollectionContributionCalendar.Weeks, and is useful for accessing the field via an interface.
func (v *contributionsViewUserContributionsCollectionContributionCalendar) GetWeeks() []contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek {
	return v.Weeks
}

// contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek includes the requested fields of the GraphQL type ContributionCalendarWeek.
// The GraphQL type's documentation follows.
//
// A week of contributions in a user's contribution graph.
type contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek struct {
	// The days of contributions in this week.
	ContributionDays []contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay `json:"contributionDays"`
}

// GetContributionDays returns contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek.ContributionDays, and is useful for accessing the field via an interface.
func (v *contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeek) GetContributionDays() []contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay {
	return v.ContributionDays
}

// contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay includes the requested fields of the GraphQL type ContributionCalendarDay.
// The GraphQL type's documentation follows.
//
// Represents a single day of contributions on GraphqlClient by a user.
type contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay struct {
	// How many contributions were made by the user on this day.
	ContributionCount int `json:"contributionCount"`
}

// GetContributionCount returns contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay.ContributionCount, and is useful for accessing the field via an interface.
func (v *contributionsViewUserContributionsCollectionContributionCalendarWeeksContributionCalendarWeekContributionDaysContributionCalendarDay) GetContributionCount() int {
	return v.ContributionCount
}

// The query or mutation executed by changeUserStatus.
const changeUserStatus_Operation = `
mutation changeUserStatus ($status: ChangeUserStatusInput!) {
	changeUserStatus(input: $status) {
		status {
			id
		}
	}
}
`

func changeUserStatus(
	ctx context.Context,
	client graphql.Client,
	status ChangeUserStatusInput,
) (*changeUserStatusResponse, error) {
	req := &graphql.Request{
		OpName: "changeUserStatus",
		Query:  changeUserStatus_Operation,
		Variables: &__changeUserStatusInput{
			Status: status,
		},
	}
	var err error

	var data changeUserStatusResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by contributionsView.
const contributionsView_Operation = `
query contributionsView ($username: String!, $from: DateTime!, $to: DateTime!) {
	user(login: $username) {
		contributionsCollection(from: $from, to: $to) {
			contributionCalendar {
				weeks {
					contributionDays {
						contributionCount
					}
				}
			}
		}
	}
}
`

func contributionsView(
	ctx context.Context,
	client graphql.Client,
	username string,
	from time.Time,
	to time.Time,
) (*contributionsViewResponse, error) {
	req := &graphql.Request{
		OpName: "contributionsView",
		Query:  contributionsView_Operation,
		Variables: &__contributionsViewInput{
			Username: username,
			From:     from,
			To:       to,
		},
	}
	var err error

	var data contributionsViewResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
