name: Update
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Generate graph
        env:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: go run main.go > contributions.svg
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'contributions.svg'
          default_author: github_actions
          message: 'Update contributions.svg'
