name: Update
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Generate graph
        env:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: go run main.go
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: assets
          FOLDER: assets
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
